apiVersion: apps/v1
kind: Deployment
metadata:
  name: uber-deployment
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: uber
  template:
    metadata:
      labels:
        app: uber
    spec:
      containers:
      - name: uber
        image: karrtiksinghh/uber:latest
        ports:
        - containerPort: 3000  

